### PR TITLE
Signup "Agree to Terms"

### PR DESCRIPTION
**Pull request by samblackk**
Attached to https://github.com/astronomer/issues/issues/43.

Adds an "agree to terms" checkbox to the signup form. 
Controls submission of both the Oauth buttons & Email/Pass form.

Screen Shot 2019-09-16 at 6 27 42 PM

Screen Shot 2019-09-16 at 6 27 50 PM

### CODE REVIEW

**Comment by schnie** [comment]
Talked with @Inkdryer a bit about this the other day in the office. I'm wondering if we can drop the checkbox, and make this more of a "notice" that goes down below all the login components. Like slightly change the verbage to be like "By signing up you are agreeing to our <terms link> and <privacy link>", or something like that. Just to avoid any awkwardness, flow-wise.

@ryw any thoughts on this one?

**Comment by ryw** [comment]
How about we move it to the trial form?

Screen Shot 2019-09-22 at 11 28 36 AM

**Comment by schnie** [comment]
@ryw makes sense for cloud, but won't we also want to show these links to Enterprise users? If so, then maybe orbit makes sense.

**Comment by schnie** [comment]
@samblackk what do you think about making this more of a notice than a required step? I'm worried about the UX of this. Obviously its a very small thing, but just doesn't feel right to me.

I randomly checked netlify, and it seems like they do the same thing.

"By signing in to Netlify, you agree to our terms of service."

**Comment by samblackk** [comment]
Totally - I'll get an update on this pushed in a bit.

**Pull request merged**
