### PR TITLE
Metrics - Reorder/Combine charts

### PR DESCRIPTION
**Pull request by samblackk**
UI update to the `Metrics` tab - reorganizes the metric modules to present data cogently. 
Also adds additional checking to show/hide the pod lists if data is present or not. 

New order:
1. Health + Core Container Status (combine)
2. Tasks  + Task Status (combine) 
3. DB Connections
4. Scheduler
5. Quotas
6. Utilization

Flow: Bias  → Actionable → Interesting

Please r/m
Attached to https://github.com/astronomer/astronomer/issues/339

### CODE REVIEW

**Comment by schnie** [comment]
@samblackk playing with this now. Wondering about the "Core Container Status" title now on the top panel. The one metric is a rollup of the pods, while the other one is an actual airflow emitted metric by the scheduler. Wondering if we should change the title to be a little more generic, maybe just "Deployment Status", or something.

**Comment by schnie** [comment]
@samblackk since we removed the task status table, I'm also wondering if we should show a graph that shows current running _count_ and maybe that count over time. Thinking it'll be useful to compare this number with what Airflow says is running. It's a little weird now the way these numbers work out, but I think its a helpful thing to know when using the `KubernetesExecutor`. Any thoughts @ryw?

**Comment by samblackk** [comment]
> Wondering if we should change the title to be a little more generic, maybe just "Deployment Status", or something.

Deployment status would work well.

**Comment by schnie** [comment]
We can handle the task count thing separately if we decide to. Merging as is for now!

**Pull request merged**
