### PR TITLE
Add AU to Brownie tooltips & total AU to resource list

### PR DESCRIPTION
**Pull request by samblackk**
Attached to https://github.com/astronomer/astronomer/issues/301

Adds more info about AU usage to the deployment config.

Screen Shot 2019-07-09 at 3 00 36 PM

@paolaperaza Does this help? 

Please r/m

### CODE REVIEW

**Comment by paolaperaza** [comment]
@samblackk Yes! Definitely helps - that's great. I don't know if it'd be worth separating total AU somehow as an aggregate standalone number that's not visually at the same level as # of pods for example, but I'll defer to you or @schnie on that - not sure what other option we'd have.

Thanks @samblackk

**Comment by schnie** [comment]
It could work on the second line since AU is directly related to the cpu/mem, like: `2AU (.2 CPU, 768 MB)`

Or bold one and not the other, or something like that.

**Comment by schnie** [comment]
@samblackk any thoughts on bumping AU to second line? If it looks weird, this works just fine!

**Comment by samblackk** [comment]
@schnie AU is moved.
Screen Shot 2019-07-15 at 10 47 33 AM

**Pull request merged**
