### PR TITLE
Switch to yarn and update to babel7 to remove security warnings

### PR DESCRIPTION
**Pull request by ashb**
The number suddenly got very high, and most of them were related to
set-values or braces a few levels down in the dep tree.

I used `babel-update` to update the babel config.

(I switched to yarn to get better control over things).

I have only given this very cursory testing, but it launches.

### CODE REVIEW

**Comment by samblackk** [comment]
Performing some build tests to ensure all the things render correctly. Sometimes updating Babel and not updating React can cause unexpected component issues.

**Comment by ashb** [comment]
@samblackk I've updated/rebsaed and have done _very_ minimal testing locally and I can log in and veiw deployments etc.

The tests are currently failing due to dropping/low test coverage on ui/Snackbar which seems odd

**Comment by schnie** [comment]
@ashb @samblackk looks like this PR has some conflicts now. If we want to switch, can we also update the production `Dockerfile` here? https://github.com/astronomer/astronomer/tree/master/docker/platform/orbit-ui

**Comment by ashb** [comment]
I'll update this tomorrow.

**Comment by samblackk** [comment]
@schnie @ashb Rebased, and tests fixed. Let's run one more manual test through it all before merging.

**Comment by schnie** [comment]
@samblackk @ashb what we think here? Looks like a little conflict, but we'll want to have a matching PR on `astronomer/astronomer` to use yarn too, right? Planning to fix this awkwardness soon.

**Comment by ashb** [comment]
> @samblackk @ashb what we think here? Looks like a little conflict, but we'll want to have a matching PR on `astronomer/astronomer` to use yarn too, right? Planning to fix this awkwardness soon.

Oh ack, yes we will.

I keep forgetting to merge this after I've resolved the conflicts. If it's worth it (if we aren't close to having Sam's rebuild soon) then I can do it. I would also like to switch Houston over to Yarn too, as I think it would have made the version issue we had this (last?) week less likely to happen.

**Comment by ashb** [comment]
Going to close this out, not worth the hassle now given the work Sam's been doing.

**Pull request closed without merging**
