### PR TITLE
Filter metrics without containers

### PR DESCRIPTION
**Pull request by samblackk**
Attached to https://github.com/astronomer/issues/issues/375

Updates `ContainerList` and `TaskStatus` list to only display metrics that return a `metric.container` value.

### CODE REVIEW

**Comment by schnie** [comment]
@samblackk do the podOperators not have this field or something?

**Comment by samblackk** [comment]
@schnie They don't. It's missing.

**Comment by schnie** [comment]
Gotcha, so this effectively hides `KubernetesPodOperator` pods from both views?

**Comment by schnie** [comment]
@dimberman @kaxil @ashb I'm wondering if we should add some "default" labels to `KubernetesExecutor` pods, as well as `KubernetesPodOperator` pods. Could probably be contributed upstream as part of the default config. This would help out a lot here.

**Comment by schnie** [comment]
Gonna go ahead and merge this in. It's too much effort to jam something into airflow to get more labels to query on. We're down to the wire here, so we'll have to follow up with something to show the pod operators later.

**Pull request merged**
