### PR TITLE
Add support of path based airflow ingress

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/459

### CODE REVIEW

**Comment by schnie** [comment]
@andriisoldatenko isn't it `/deployments/{{ .Release.Name }}/airflow`? How do these end up looking when rendered?

**Comment by andriisoldatenko** [comment]
may be you didn’t have a chance to review thread with Sam, but she suggested ``${u.url}/deployments/airflow``
which in practice:
`http://app.local.astronomer.io:5000/workspaces/ck5i84g5700l507073s25y9i3/deployments/deployments/https://new-flux-7162-airflow.local.astronomer.io//airflow`
i can’t find where we build this url… in orbit-ui

**Comment by andriisoldatenko** [comment]
cc @samblackk

**Comment by samblackk** [comment]
Working on this

**Comment by andriisoldatenko** [comment]
@samblackk ty!

**Comment by andriisoldatenko** [comment]
@samblackk i fixed it in houston https://github.com/astronomer/houston-api/pull/211
as @schnie suggested.

**Pull request closed without merging**
