### PR TITLE
Update Workspace Routing

### PR DESCRIPTION
**Pull request by samblackk**
Completely overhauls the workspace -> deployment routing.
Fixes all the issues we're having with `$workspaceUuid` undefined when navigating the application.

**May need many a hard refresh**

Please r/m

### CODE REVIEW

**Comment by samblackk** [comment]
Hold up. There's an issue when saving deploy config - form saves fine, but the component disappears.

**Comment by schnie** [comment]
@samblackk looks like the trial bar links to /billing still

**Comment by schnie** [comment]
Took care of the billing links I think.

**Comment by schnie** [comment]
@samblackk looks like `deployment.workspace.id` ends up `null` after submitting the form up around here - https://github.com/astronomer/orbit-ui/blob/fix/workspace-routing/src/modules/deployments/Deployment/Module.js#L56.

After form submission, all deployment level tabs are blank.

**Comment by schnie** [comment]
Added `deployment.workspace.id` to houston fragment to ensure - https://github.com/astronomer/houston-api/commit/bf4ac29f9ac95298960ef24d9e1d06d75364ebb6.

This fixes this problem

**Comment by schnie** [comment]
@samblackk found one more thing. If you navigate down to a deployment from the Admin panel, then go to the service accounts tab, the active workspace in the nav, switches from "Admin" to my email, and if I click it, it shows a DAG Gone it. Also looks like the "Service Accounts" isn't highlighted in the sub menu.

**Comment by schnie** [comment]
Actually, I think the menu highlighting was prob already slightly messed up.

**Comment by samblackk** [comment]
The `DAG! Gone it` from admin -> deployment -> service account is due to RBAC, getting ```[GraphQL error]: Message: You do not have the appropriate permissions for thatLocation: [{"line":2,"column":3}],, Path: serviceAccounts``` in console

**Comment by samblackk** [comment]
The menu switch has always been that way - because the service-account page is shared between both workspace & deployment screens.

**Pull request merged**
